[Java] classes - new exercise
exercism/v3 pull request #2179
Opened 2020-08-15 07:42 UTC by mikedamay

All files complete except java/config.json and exercises/settings.gradle which I will update before merging

2020-09-01 19:26 UTC, mirkoperillo commented
Hi @mikedamay sorry for the late, I was offline for my summer holidays
I'll provide you a review ASAP

Thank you for contributing to Java track

2020-09-03 15:38 UTC, mirkoperillo requested changes
@mikedamay thank you for your help.
The work is good, it needs only some minor changes before the merging

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/.docs/after.md
> +```csharp
replace `csharp` with `java`. 
This is valid for other blocks of the page

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/.docs/after.md
> +It is customary to specify an access modifier for all members. If no access modifier is specified, it will default to `private`.
In Java if no access modifier is specified, the default one is `package visibility`.
So the member is visible to all classes defined into the same package

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/.docs/after.md
> +{
normally in Java left curly bracket is on the same line of the class name
so 
```
class Car {
}
```
This is valid for all the code in this page
This is valid for block of code too

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/.docs/instructions.md
> +```csharp
replace `csharp` with `java`. 
This is valid for other blocks of the page

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/.docs/introduction.md
> +```csharp
replace `csharp` with `java`. 
This is valid for other blocks of the page

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/.docs/introduction.md
> +{
normally in Java left curly bracket is on the same line of the class name
so 
```
class Car {
}
```
This is valid for all the code in this page
This is valid for block of code too

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/.meta/src/reference/java/RemoteControlCar.java
> +{
normally in Java left curly bracket is on the same line of the class name
so 
```
class Car {
}
```
This is valid for all the code in this page
This is valid for block of code too

2020-09-03 15:38 UTC, mirkoperillo commented on languages/java/exercises/concept/classes/src/test/java/RemoteControlCarTest.java
> +{
normally in Java left curly bracket is on the same line of the class name
so 
```
class Car {
}
```
This is valid for all the code in this page
This is valid for block of code too

2020-09-08 10:42 UTC, mikedamay commented
Thanks for the review - all points have been addressed.  I will update config.json before merging

2020-09-09 14:49 UTC, mirkoperillo commented
@mikedamay thank you for dedicating time to this: the markdown part looks good, you miss only fixing the code part and the review can be consider ok

2020-09-09 17:27 UTC, mikedamay commented
Done

2020-09-10 13:40 UTC, mirkoperillo approved these changes

2020-09-10 13:41 UTC, mirkoperillo commented
@mikedamay thank you, LGTM.

You can add missing stuff in `exercises/settings.gradle` and `java/config.json` and merge it when you want.

2020-09-11 07:58 UTC, merged