[Ruby] Update log line level instructions
exercism/v3 pull request #2289
Opened 2020-10-06 14:00 UTC by jonathanyeong

It now follows the same format as the other instruction files for Ruby.

Fix as discussed here: https://github.com/exercism/v3/issues/2055#issuecomment-702999038

2020-10-06 16:35 UTC, kotp approved these changes
Looks good

2020-10-06 16:37 UTC, kotp requested changes
Sorry, the rest look like this:

```markdown
## 1. Calculate the interest rate

Implement the `SavingsAccount.interest_rate` method to calculate the interest rate based on the specified balance:
```

2020-10-06 16:39 UTC, kotp commented
> Sorry, the rest look like this:
> 
> ```gfm
> ## 1. Calculate the interest rate
> 
> Implement the `SavingsAccount.interest_rate` method to calculate the interest rate based on the specified balance:
> ```

This means that this should not be the only file changed.  Can you add the others?  Prefer the `Class#your_method_to_implement` pattern.

2020-10-07 03:20 UTC, jonathanyeong commented
@kotp I believe we're following this format:

> @iHiD wants to use <CLASS>.<METHOD> for class methods, and <CLASS>#<METHOD> for instance methods.

The `LogLineParser` methods are all class methods, which is why I used the dot notation. Let me know if that doesn't match your expectations!

2020-10-07 03:44 UTC, kotp approved these changes

2020-10-07 03:45 UTC, kotp commented
You are right... I misread.

2020-10-07 03:48 UTC, merged

2020-10-07 03:48 UTC, kotp commented
Thank you @jonathanyeong