[JavaScript] Add Concept Exercise: type-conversion
exercism/v3 pull request #2563
Opened 2020-10-29 08:12 UTC by shubhsk88

The PR addresses issue #1892  which is the implementation of the new exercise for type-conversion in javascript

2020-11-01 00:57 UTC, SleeplessByte commented
Started reviewing this. It's coming!

2020-12-04 01:07 UTC, neenjaw requested changes
I think the only change that _must_ be done is changing the after.md into a concept about.md with a links.json.

The rest is pretty good (:tada: :tada:) and if you don't want to make the changes, it should have an improvement issue opened.

@SleeplessByte is busy, but it would also  be good to have his eye on this as well.

Great work!

2020-12-04 01:07 UTC, neenjaw commented on languages/javascript/exercises/concept/type-conversion/.docs/hints.md
> +- Sum the result of the two converted number
```suggestion
- Sum the result once each number is converted
```

2020-12-04 01:07 UTC, neenjaw commented on languages/javascript/exercises/concept/type-conversion/.docs/hints.md
> +## 1. Calculate the sum of those two array
```suggestion
## 1. Find the sum of two arrays
```

2020-12-04 01:07 UTC, neenjaw commented on languages/javascript/exercises/concept/type-conversion/.docs/instructions.md
> +## Calculate the sum of those two array
```suggestion
## 1. Find the sum of two arrays
```

2020-12-04 01:07 UTC, neenjaw commented on languages/javascript/exercises/concept/type-conversion/.docs/hints.md
> +## 2. Calculate the function which tells us the owner whether the number is lucky or not
```suggestion
## 2. Determine if the number is lucky
```

2020-12-04 01:07 UTC, neenjaw commented on languages/javascript/exercises/concept/type-conversion/.docs/instructions.md
> +## 2. Calculate the function which tells us the owner whether the number is lucky or not
```suggestion
## 2. Determine if the number is lucky
```

2020-12-04 01:07 UTC, neenjaw commented on languages/javascript/exercises/concept/type-conversion/.docs/hints.md
> +- Convert the number into string and then convert it into the array and finally join the string using the function to `join` the array using dash
Try not to give away the solution with the hint.

```suggestion
- Use type conversion to change the number to a string
- Strings have methods which can be used to break them apart
- Arrays have a method to merge elements into a string
```

You could apply this to each hint as well

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/after.md
> +[ecma docs]: https://www.ecma-international.org/ecma-262/#sec-abstract-operations
I agree with this.

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/instructions.md
> +He decide to send the result of this number to his partner to make it easy for him to read
```suggestion
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/instructions.md
> +
```suggestion

He decides to send the result of this number to his partner to make it easy for him to read
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/instructions.md
> +
```suggestion

```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/instructions.md
> +Implement a function to determine whether the number is lucky for him or not.
```suggestion
After the calculator the owner would like to know the sum that he got is a lucky number or not.

A number is said to be lucky if the the reverse of the number is the same

Implement a function to determine whether the number is lucky for him or not.
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/introduction.md
> +Type Conversion is often referred when converting the value from one data type to another data type.This is also often referred as "Coercion".
```suggestion
Type Conversion is the act of converting the value from one data type to another data type. This is also often referred as "Coercion".
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/introduction.md
> +There are two ways to do the type conversion
```suggestion
Type conversion may be explicit or implicit.
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/introduction.md
> +explicit:
```suggestion
Explicit type conversion are performed by a function call _meant to convert the type_:
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/introduction.md
> +The other one is the implicit conversion are type conversion which is usually hidden and they are more non-obvious
```suggestion
Implicit conversion happens as a side-effect of an operation:
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/introduction.md
> +console.log(`There are ${a} cats in the house`) // Number=>String
```suggestion
console.log(`There are ${a} cats in the house`) 
// Implicitly converts from Number to String in order to insert the value of a into the template literal.
```

2020-12-30 17:17 UTC, SleeplessByte commented on languages/javascript/exercises/concept/type-conversion/.docs/introduction.md
> +```
They are type-conversions. They're not what's traditionally known as "casts".

2021-01-15 17:53 UTC, SleeplessByte commented
@shubhsk88 hows' this going?

2021-01-15 18:27 UTC, shubhsk88 commented
> @shubhsk88 hows' this going?

Sorry for the delay .Bro this and the other  abstract equality one will be done by this weekend .got busy with some work but will do it

2021-01-17 04:18 UTC, SleeplessByte submitted a review, later dismissed
I think something went wrong here. It's changing almost every file from every track. Did you attempt to rebase?

2021-01-17 04:22 UTC, shubhsk88 commented
> I think something went wrong here. It's changing almost every file from every track. Did you attempt to rebase?

I think there was some change in the the way exercise were organised and when I tried to pull it,it just have too much changes could you help me to do that @SleeplessByte

2021-01-17 05:04 UTC, SleeplessByte commented
It's probably easiest to do this:

1. Grab the new exercise directory
2. Put it somewhere safe
3. Delete the branch
4. Make sure main/master is up to date
5. Create branch with the same name you just deleted
6. Put back the exercise directory
7. Commit it
8. Force push (same upstream)

2021-01-17 16:23 UTC, neenjaw commented
PR Fixed :P

2021-01-17 17:53 UTC, neenjaw approved these changes

2021-01-17 17:56 UTC, merged