Fix exercise's link
exercism/v3 pull request #2922
Opened 2020-12-12 09:05 UTC by Limm-jk

I corrected the changes to the exercise I worked on.

2020-12-12 10:49 UTC, BethanyG commented
Hi @Limm-jk!  You need to run `prettier` or the `/format` command on this PR once you've made your change.  😄   Otherwise, the CI test will fail.

2020-12-12 10:52 UTC, BethanyG requested changes

2020-12-12 10:52 UTC, BethanyG commented on languages/python/exercises/README.md
> +| [`numbers-I`](https://github.com/exercism/v3/tree/master/languages/python/concepts/numbers)             | [Currency Exchange](https://github.com/exercism/v3/tree/master/languages/python/exercises/c
```suggestion
| [`numbers`](https://github.com/exercism/v3/tree/master/languages/python/concepts/numbers)             | [Currency Exchange](https://github.com/exercism/v3/tree/master/languages/python/exercises/concept/currency-exchange)                                                                    | `numbers`, `ints`, `floats`, arithmetic | [numbers](https://github.com/exercism/v3/blob/master/languages/python/exercises/concept/currency-exchange/.meta/design)                                                                                | `basics`                                                                                                                 |
```

2020-12-12 10:55 UTC, BethanyG commented
oof. I think that the bot and I crossed wires.  See my comment above.  Unfortunately, I don't think it will allow you or me to auto-commit that one.  Let me try to make the suggestion again.

2020-12-12 10:58 UTC, BethanyG commented on languages/python/exercises/README.md
> +| [`numbers-I`](https://github.com/exercism/v3/tree/master/languages/python/concepts/numbers)             | [Currency Exchange](https://github.com/exercism/v3/tree/master/languages/python/exercises/c
```suggestion
| [`numbers`](https://github.com/exercism/v3/tree/master/languages/python/concepts/numbers)             | [Currency Exchange](https://github.com/exercism/v3/tree/master/languages/python/exercises/concept/currency-exchange)| `numbers`, `ints`, `floats`, arithmetic | [numbers](https://github.com/exercism/v3/blob/master/languages/python/exercises/concept/currency-exchange/.meta/design)                                                                                | `basics`                                                                                                                 |
```

2020-12-12 10:58 UTC, BethanyG approved these changes

2020-12-12 10:59 UTC, BethanyG commented
_**sigh**_

/format

2020-12-12 11:02 UTC, merged

2020-12-12 12:05 UTC, Limm-jk commented
Was there a problem? 
Was there a problem with me? 
If you let me know, I will apply it to future contributions.

2020-12-12 12:23 UTC, BethanyG commented
No!  I just noticed that I needed to change the name of the _concept_ to just `numbers`.  I also needed to change the link to the design file from the issue to the `currency-exchange/design.md` file.  And since I made those suggestions/changes right as you were running `/format`, we sort of stepped on each other.  So - **it was my fault!**.  Apologies for that.

2020-12-12 12:30 UTC, BethanyG commented
running `/format` in the repo can sometimes choke as well.  If your PR is coming from a fork, you have to close the PR and then re-open it to get the CI to run again - which is _totally fine_ (although it often doesn't work for me, and I usually have to try twice 😀 ).  

You can also set up prettier (the auto-formatter we are using) to run in your code editor/IDE, if that works better:  [setting up prettier](https://prettier.io/docs/en/editors.html).  I often end up running prettier in both places (locally and in the repo) - because I am always forgetting. 😝

2020-12-13 10:13 UTC, Limm-jk commented
hahaha
I'll keep that in mind and apply it between activities from now on.
Thank you!