[Scala] Extract conceptions of rna_transcription exercise
exercism/v3 pull request #644
Opened 2020-02-11 02:24 UTC by outkaj

2020-02-11 09:44 UTC, ErikSchierboom reviewed
This is looking great! Some Concepts that might be added too:

- generics (for option definition)
- strings: input parameter
- immutability: use `val` to define mapping

2020-02-11 17:52 UTC, leobenkel requested changes

2020-02-11 17:52 UTC, leobenkel commented on languages/scala/reference/exercise-concepts/rna-transcription.md
> +- foldRight: collapse a sequence from inside to outside
This is under the `collection - reduce` main concept i think.

2020-02-11 17:52 UTC, leobenkel commented on languages/scala/reference/exercise-concepts/rna-transcription.md
> +- Option: `Option` is used as return result
Maybe something about `null handling` ?

2020-09-24 08:52 UTC, ErikSchierboom commented
@outkaj Is there anything I can do to help with this PR?

2021-01-26 13:34 UTC, ErikSchierboom commented
This Friday (Jan 29th 2021), we're going to explode this repo back into the individual track repositories and archive this repo.

As such, this PR needs to be merged by Friday 9am UTC, or it will need to be manually reopened against the track repo.

2021-08-31 10:48 UTC, closed without merging